export const classEnums = {
  CLASS: 'Class',
  MILESTONE: 'Milestone',
  UNIFORM: 'Uniform',
  TOTAL: 'Total',
  CLAIMED: 'Claimed',
  RECEIVED: 'Received',
  BILL_INVOICE: 'Bill Invoice',
  SUBMISSION_DATE: 'Submission Date',
  STATUS: 'Status',
  ACTION: 'Action',
  APPROVED: 'Approve',
  REJECTED: 'Reject',
  ADD_MILESTONE: 'Add Milestone',
  EDIT_MILESTONE: 'Edit Milestone',
  EDIT: 'Edit',
  ADD: 'Add',
  REMARKS: 'Remarks',
  CLASS_DETAILS: 'Class Details',
  SR_NO: 'SrNo',
  BATCH_ID: 'Batch ID',
  COURSE_NAME: 'Course Name',
  COURSE_HOURS: 'Course Hours',
  ENROLLED_CANDIDATES: 'Enrolled Candidates',
  PLACED_CANDIDATES: "Placed Candidates",
  BATCH_START_DATE: 'Batch Start Date',
  TOTAL_HOURS: 'Total Hours',
  ASSESSED_CANDIDATES: 'Assessed Candidates',
  DROPOUT_CANDIDATES: 'Dropout Candidates',
  BATCH_END_DATE: 'Batch End Date',
  RATE_PER_HOUR: 'Rate Per Hour',
  CERTIFIED_CANDIDATES: 'Certified Candidates',
  YES: 'Yes',
  BILL_TITLE: 'Approve Bill',
  billApprove:"Are you sure you want to approve this bill?",
  exportClass:"Export Class",
  classData: [
    {
      BatchId: "BATCH/10012/10/2021",
      StartDate: "17/10/2022",
      EndDate: "02/02/2023",
      courseName: "Fashion Design",
    },
    {
      BatchId: "BATCH/10012/10/2022",
      StartDate: "17/10/2022",
      EndDate: "02/02/2023",
      courseName: "Graphic Design",
      enrolledCandidates: "200",
      placedCandidates: "180",
      totalHours: "100",
      assessedCandidates: "190",
      dropoutCandidates: "5",
      ratePerHour: "100",
      certifiedCandidates: "185",

    },
  ],
  initialData: [
    {
      id: 1,
      mileStone: "Milestone 1",
      uniform: "1000",
      total: "100",
      claimed: "50",
      received: "45",
      billInvoice: "123",
      submissionDate: "01/01/2023",
      status: "Pending",
      remarks: "",
    },
    {
      id: 2,
      mileStone: "Milestone 2",
      uniform: "1000",
      total: "200",
      claimed: "100",
      received: "90",
      billInvoice: "456",
      submissionDate: "02/01/2023",
      status: "Approved",
      remarks: "Changed invoice due to some reason",
    },
    {
      id: 3,
      mileStone: "Milestone 3",
      uniform: "1000",
      total: "300",
      claimed: "150",
      received: "135",
      billInvoice: "789",
      submissionDate: "03/01/2023",
      status: "Pending",
      remarks: "",
    },
  ],
}
export const classView = classEnums.classData[1];