export const batchallocationLabel = {
  title: "Batch Creation",
  createBtach: "Create Batch",
  candidateList: "Candidate List",
  create: "Create",
  cancel: "Cancel",
  selectCourse: "Select Course",
  course: "course",
  batchList: "Batch List",
  candidateLable: "Candidate Name",
  mobileNo: "Mobile No",
  candidateKey: "candidate_name",
  mobileNoKey: "mobile_no",
  conatactKey: "contact_no",
  bacthNameKey: "batch_id",
  batchName: "Batch Id",
  startDate: "Start Date",
  endDate: "End Date",
  qpCode: "Qp Code",
  courseName: "Course Name",
  totalCandidate: "Total Candidate",
  totalCandidateKey: "no_of_student",
  courseNameKey: "course.course_name",
  action: "Action",
  actionKey: "action",
  editBatch: "Edit Batch",
  searchBar: "Search",
  courseId: "courseId",
  addSelecte: "Add Selected Candidate",
  status: "status",
  statusUpdateTitle: "Status Update",
  submit: "Submit",
  noOfStudent: "Number of Candidate",
  duration: "Duration (In days)",
  durationKey: "Duration",
  endTime: "End Time",
  startTime: "Start Time",
  centerName: "Center Name",
  totalEnrolled: "Total Enrolled Candidate",
  totalEnrolledKey: "batchAssign.length",
  centerKey: "center.center_name",
};

export const batchallocationValidation = {
  batchNameValidation: "Batch Id",
  startDateValidation: "start date",
  endDateValidation: "End date",
  startTimeValidation: "Start Time",
  endTimeValidation: "End Time",
  durationValidation: "Duration",
  noOfCandidateValidation: "No Of Candidate",
  endTime: "End time must be greater than start time",
};

export const editBatchLable = {
  importData: "importData",
  candidateName: "Candidate Name",
  contactNumber: "Contact Number",
  candidateNameKey: "candidate.candidate_name",
  can_idKey: "candidate.can_id",
  emp_idKey: "candidate.emp_id",
  can_id: "Can_id",
  emp_id: "Emp_id",
  contactNoKey: "candidate.contact_no",
  addMore: "Add More Candidate",
  import: "Import",
  export: "Export",
  delete: "Delete",
  deleteBody: "Are you sure you want to delete selected record?",
  uploadImage: "Upload File",
  imageUpload: "Upload Image",
  errorSizeImage: "File size should be less than 1MB",
  upoladImage: "Upload",
  importFile: "Import File",
  file: "File",
  csvValidate: "Only CSV files are allowed",
  fileType: "fileType",
  dateValidation: "End date must be greater than start date",
};

export const StatusOptions = [
  { id: 0, value: "", label: "Select Status" },
  { id: 1, value: "Completed", label: "Completed" },
  { id: 2, value: "In Progress", label: "In Progress" },
];
export const DataError = "Data is not imported due to below errors";
export const BatchListTitle = "Batch List";
export const BatchEditTitle = "Edit Batch";
export const AddCandidate = "Add More Candidate";
