export const hrEnums = {
    SR_NO: "Sr No.",
    STAFF_NAME: 'Staff Name',
    CONTACT_NO: 'Contact Number',
    EMAIL_ID: 'Email ID',
    JOINING_DATE: 'Joining Date',
    ACTION: 'Action',
    EDIT: 'Edit',
    VIEW: 'View',
    ADD: "Add",
    ID: "ID",
    DISCARD: 'Discard',
    STAFF: 'Staff',
    PROFILE_INFO: 'Profile Information',
    GENERAL_INFO: 'General Information',
    PERSONAL_INFO: 'Personal Information',
    EMPLOYMENT_INFO: 'Employment Information',
    BANK_INFO: 'Bank Information',
    FIRST_NAME: 'First Name',
    MIDDLE_NAME: 'Middle Name',
    LAST_NAME: 'Last Name',
    DESIGNATION: 'Designation',
    STAFF_TYPE: 'Staff Type',
    REPORTING_MANAGER: 'Reporting Manager',
    SALARY_CYCLE: 'Salary Cycle',
    WEEK_OFF: 'Week Off',
    HOLIDAY_TEMPLATE: 'Holiday Template',
    LEAVE_TEMPLATE: 'Leave Template',
    SHIFT: 'Shift',
    SALARY_ACCESS: 'Salary Access',
    ATTENDANCE_MODE: 'Attendance Mode',
    EMAIL: 'Email',
    GENDER: 'Gender',
    DOB: 'Date of Birth',
    MARITAL_STATUS: 'Marital Status',
    BLOOD_GRP: 'Blood Group',
    EMERGENCY_CONTACT: 'Emergency Contact',
    PHYSICALLY_CHALLENGED: 'Physically Challenged',
    FATHER_NAME: "Father's Name",
    MOTHER_NAME: "Mother's Name",
    SPOUSE_NAME: "Spouse Name",
    CURRENT_ADDRESS: 'Current Address',
    PERMANENT_ADDRESS: 'Permanent Address',
    ADDRESS_LINE1: 'Address Line1',
    ADDRESS_LINE2: 'Address Line2',
    STATE: 'State',
    CITY: 'City',
    POSTAL_CODE: 'Postal Code',
    UAN: 'UAN',
    PAN: 'PAN',
    AADHAR_NUMBER: 'Aadhar Number',
    NAME_OF_BANK: 'Name of Bank',
    IFSC_CODE: 'IFSC Code',
    ACCOUNT_NO: 'Account Number',
    ACCOUNT_HOLDER_NAME: 'Name of Account Holder',
    option: [
        { label: "option1", value: "Option1" },
        { label: "option2", value: "Option2" },
    ],
    radio_option: [
        { label: "Yes", value: "Yes" },
        { label: "No", value: "No" },
    ],
    classData: [
        {
            id: "1",
            staff_name: "Mohan Das",
            contact: "9826472999",
            email_id: "xyz@gmail.com",
            joining_date: "10/05/2023",
        },
        {
            id: "2",
            staff_name: "Amit Kumar",
            contact: "9826472518",
            email_id: "xyz@gmail.com",
            joining_date: "02/02/2023",
        },
    ],
    staffData:
    {
        first_name: "Mohan",
        middle_name: "Ram",
        last_name: "Kumar",
        designation: "Option1",
        id: "23",
        staff_type: "Regular",
        contact_no: "9012345823",
        reporting_manager: "Amit Das",
        salary_cycle: "1",
        week_off: "Sunday",
        holiday_template: "holiday",
        leave_template: "leave policy",
        shift: "10AM to 8PM",
        salary_access: "Disable",
        attendance_mode: "Manual Attendance",
        email: "mohan@gmail.com",
        gender: "male",
        dob: "10/05/1995",
        marital_status: "Single",
        blood_group: "O+",
        emergency_contact: "9826472999",
        father_name: "Ram Sharma",
        mother_name: "Vidhya Sharma",
        spouse_name: "N/A",
        physically_challenged: "No",
        address_line1: "Solaris",
        address_line2: "Bhuyangdev",
        city: "Ahmedabad",
        state: "Gujarat",
        postal_code: "382330",
        joining_date: "10/05/2023",
        uan: "9826472999947397",
        pan: "GTIO4653",
        aadhar: "965327658123",
        bank_name: "SBI",
        ifsc_code: "98264729999826472",
        account_number: "SBI76290",
        account_holder_name: 'Amit Kumar',
    },

}