export const hostelLabel = {
  batchId: "Batch Id",
  fromDate: "From Date",
  toDate: "To Date",
  days: "Days",
  fromDate: "From Date",
  toDate:"To Date",
  claimedBill: "Claimed Bill",
  received: "Received",
  submissionDate:"Submission Date",
  invoiceNo: "Bill Invoice",
  month: "Month",
  projectValued: "Projection Valued",
  centerName:"Center:",
  batchName :"Batch Id:",
  BatchStartDate:"Batch Start Date:",
  BatchEndDate:"Batch End Date:",
  courseName:"Course Name:",
  hostelDetails:"Hostel Details",
  remarks:"Remarks",
  status:"Status",
  centerDetails:"Center Details",
  billApprove:"Are you sure you want to approve this bill?",
  approve:"Approved",
  pending:"Pending",
  reject:"Rejected",
  yes:"Yes",
  hostelList:"Hostel List",
  center:"Center Name",
  course:"Course Name",
  batchStart:"Start Date",
  endDate:"End Date",
  approveBill:"Approve Bill",
  addHostelDlt:"Add Hostel",
  search:"Search",
  exportHostel: "Export Hostel"
};

export const radioOptions1 = [
  { id: "radioi1", value: "Yes", label: "Yes", labelSuffix: "" },
  { id: "radioi2", value: "No", label: "No", labelSuffix: "" },
];
export const StatusOptions = [
  { id: 0, value: "", label: "Select Status" },
  { id: 1, value: "Pending", label: "Pending" },
  { id: 2, value: "Rejected", label: "Rejected" },
  { id: 3, value: "Approved", label: "Approved" },
];